name: Build and Publish Docker Image

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-and-push-docker:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Log in to GHCR
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/fast-jl-binary:latest
                      ghcr.io/${{ github.repository_owner }}/fast-jl-binary:${{ github.sha }}
