name: Build and Publish Python Wheel

on:
    workflow_dispatch:
    push:
        tags:
            - "v*" # Only publish on tags that start with 'v'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Build wheel using Docker
              run: |
                  ./run.sh
            - name: Copy to tmp folder
              run: |
                  mkdir tmp
                  cp -r output/fast_jl* tmp/

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Change metadata
              run: |
                  uv tool run wheel unpack tmp/* -d dist
                  rm tmp/*.whl
                  find tmp -name METADATA -exec sed -i   -e 's/^Author:.*/Author: Dariush Wahdany/'   -e 's/^Author-email:.*/Author-email: dariushwahdany@gmail.com/'   -e 's/^Name: fast_jl/Name: fast_jl_binary/'   {} \;
                  uv tool run wheel pack tmp/* -d dist
            - name: Copy to dist folder
              run: |
                  mkdir dist
                  cp -r tmp/*.whl dist/

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
